options:
  prev_tag: "versio-prev"

projects:
  - name: "readable-name-generator"
    id: 1
    tag_prefix: ""
    labels: cargo
    version:
      file: "Cargo.toml"
      toml: "package.version"
    hooks:
      post_write: 'cargo update --workspace'

sizes:
  use_angular: true
  none: [ci, '-']
