[package]
name = "readable-name-generator"
description = "Generate a readable name for throwaway infrastructure"
version = "2.100.50"
edition = "2021"
license = "CC0-1.0"
repository = "https://github.com/PurpleBooth/anarchist-readable-name-generator-lib.git"
keywords = ["names", "utility"]
categories = ["development-tools::testing","command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
anarchist-readable-name-generator-lib = "0.1.1"
clap_complete = "3.2.3"
clap = { version = "3.2.21", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.39"
