on:
  push:
    branches:
      - master
name: Development Release
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: purplebooth/readable-name-generator/readable-name-generator
          username: PurpleBooth
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
