name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:
jobs:
  lint-markdown:
    uses: PurpleBooth/common-pipelines/.github/workflows/markdown-check.yml@main
  rust-checks:
    uses: PurpleBooth/common-pipelines/.github/workflows/rust-check.yml@main
  specdown:
    uses: PurpleBooth/common-pipelines/.github/workflows/specdown-check.yml@main
  docker-build:
    uses: PurpleBooth/common-pipelines/.github/workflows/docker-build.yml@main

  flatpak-build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44@sha256:576ffb90b2456ee3dbb6cb2ccd8b2a85273d0e95c142a2f0861cb0b51123d166
      options: --privileged
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@df610e76bc0eabff41ffaa7953f6d03123e9e26a # v6
        with:
          bundle: readable-name-generator.flatpak
          manifest-path: io.github.PurpleBooth.readable-name-generator.yml
          cache-key: flatpak-builder-${{ github.sha }}

  release:
    if: github.ref == 'refs/heads/main'
    needs:
    - docker-build
    - flatpak-build
    - specdown
    - lint-markdown
    - rust-checks
    outputs:
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - uses: cargo-bins/cargo-binstall@main
      name: Install cargo binstall
    - name: Get tags
      run: git fetch --tags origin
    - shell: bash
      run: cargo binstall --no-confirm cargo-edit
    - shell: bash
      run: cargo binstall --no-confirm --locked cocogitto
    - id: previous_version
      run: |
        cog get-version | tee .version
        echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
        rm .version
      shell: bash
    - name: Semver release
      id: release
      run: |
        git config --global user.name "cog-bot"
        git config --global user.email "cog@example.com"
        cog bump --auto
    - id: current_version
      run: |
        cog get-version | tee .version
        echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
        rm .version
      shell: bash

  docker-push:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
    - release
    uses: PurpleBooth/common-pipelines/.github/workflows/docker-push.yml@main
    with:
      current_version: ${{ needs.release.outputs.current_version }}

  release-binary:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
    - release
    uses: PurpleBooth/common-pipelines/.github/workflows/release-rust-binary.yml@main
    with:
      current_version: ${{ needs.release.outputs.current_version }}
      previous_version: ${{ needs.release.outputs.previous_version }}
    secrets:
      cargo_token: ${{ secrets.CARGO_TOKEN }}
      committer_token: ${{ secrets.COMMITTER_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

  release-flatpak:
    permissions:
      id-token: write
      attestations: write
      contents: write
    runs-on: ubuntu-latest
    needs:
      - release-binary
      - release
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44@sha256:576ffb90b2456ee3dbb6cb2ccd8b2a85273d0e95c142a2f0861cb0b51123d166
      options: --privileged
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2 # v1
        with:
          tag: v${{ needs.release.outputs.current_version }}
          fileName: 'readable-name-generator-x86_64-unknown-linux-gnu.sha256'
      - run: echo "hash=$( cut -f1 -d' ' < readable-name-generator-x86_64-unknown-linux-gnu.sha256 )" >> "$GITHUB_OUTPUT"
        shell: bash
        id: release_sha
      - uses: mikefarah/yq@bbdd97482f2d439126582a59689eb1c855944955 # v4.44.3
        with:
          cmd: yq -i '.modules[0].sources[0].url = strenv(URL)' io.github.PurpleBooth.readable-name-generator.yml
        env:
          URL: https://github.com/PurpleBooth/readable-name-generator/releases/download/v${{ needs.release.outputs.current_version }}/readable-name-generator-x86_64-unknown-linux-gnu
      - uses: mikefarah/yq@bbdd97482f2d439126582a59689eb1c855944955 # v4.44.3
        with:
          cmd: yq -i '.modules[0].sources[0].sha256 = strenv(URL_SHA)' io.github.PurpleBooth.readable-name-generator.yml
        env:
          URL_SHA: ${{ steps.release_sha.outputs.hash }}
      - uses: flatpak/flatpak-github-actions/flatpak-builder@df610e76bc0eabff41ffaa7953f6d03123e9e26a # v6
        with:
          bundle: readable-name-generator.flatpak
          manifest-path: io.github.PurpleBooth.readable-name-generator.yml
          cache-key: flatpak-builder-${{ github.sha }}
      - name: Attest binaries
        uses: actions/attest-build-provenance@310b0a4a3b0b78ef57ecda988ee04b132db73ef8 # v1
        with:
          subject-path: readable-name-generator.flatpak
      - run: gh release upload "$RELEASE_TAG" readable-name-generator.flatpak
        env:
          RELEASE_TAG: v${{ needs.release-binary.outputs.current_version }}