name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:
jobs:
  lint-markdown:
    uses: PurpleBooth/common-pipelines/.github/workflows/markdown-check.yml@main
  rust-checks:
    uses: PurpleBooth/common-pipelines/.github/workflows/rust-check.yml@main
  specdown:
    uses: PurpleBooth/common-pipelines/.github/workflows/specdown-check.yml@main
  docker-build:
    uses: PurpleBooth/common-pipelines/.github/workflows/docker-build.yml@main
  nfpm-build:
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -y nfpm
      - uses: dtolnay/rust-toolchain@master
        name: Install rust toolchain
        with:
          toolchain: stable
      - shell: bash
        run: |
          function build_for() {
            (
              ARGE="$1"
              rustup target add "$ARGE"
              cd "./target/$ARGE/release"
              cargo build --release --target="$ARGE"
              nfpm pkg --packager archlinux --target ./../../../target/
              nfpm pkg --packager rpm --target ./../../../target/
              nfpm pkg --packager apk --target ./../../../target/
              nfpm pkg --packager deb --target ./../../../target/
              cargo clean --target "$ARGE"
            )
          }

          build_for aarch64-unknown-linux-gnu
          build_for x86_64-unknown-linux-gnu

  release:
    if: github.ref == 'refs/heads/main'
    needs:
    - docker-build
    - specdown
    - lint-markdown
    - rust-checks
    outputs:
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - uses: cargo-bins/cargo-binstall@main
      name: Install cargo binstall
    - name: Get tags
      run: git fetch --tags origin
    - shell: bash
      run: cargo binstall --no-confirm cargo-edit
    - shell: bash
      run: cargo binstall --no-confirm --locked cocogitto
    - id: previous_version
      run: |
        cog get-version | tee .version
        echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
        rm .version
      shell: bash
    - name: Semver release
      id: release
      run: |
        git config --global user.name "cog-bot"
        git config --global user.email "cog@example.com"
        cog bump --auto
    - id: current_version
      run: |
        cog get-version | tee .version
        echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
        rm .version
      shell: bash

  docker-push:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
    - release
    uses: PurpleBooth/common-pipelines/.github/workflows/docker-push.yml@main
    with:
      current_version: ${{ needs.release.outputs.current_version }}

  release-binary:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
    - release
    uses: PurpleBooth/common-pipelines/.github/workflows/release-rust-binary.yml@main
    with:
      current_version: ${{ needs.release.outputs.current_version }}
      previous_version: ${{ needs.release.outputs.previous_version }}
    secrets:
      cargo_token: ${{ secrets.CARGO_TOKEN }}
      committer_token: ${{ secrets.COMMITTER_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
