
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  test-windows:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v1
      - run: make test-universal
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v1
      - run: make test

  build:
    needs: [test, test-windows]
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Upload Release Asset
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - run: |
          make build
      - uses: actions/upload-artifact@master
        with:
          name: readable-name-generator-${{ matrix.platform }}
          path: ./readable-name-generator
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - uses: actions/download-artifact@master
      with:
        name: readable-name-generator-ubuntu-latest
    - uses: actions/download-artifact@master
      with:
        name: readable-name-generator-macos-latest
    - uses: actions/download-artifact@master
      with:
        name: readable-name-generator-windows-latest
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./readable-name-generator-ubuntu-latest/readable-name-generator
        asset_name: readable-name-generator-ubuntu
        asset_content_type: application/octet-stream
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./readable-name-generator-macos-latest/readable-name-generator
        asset_name: readable-name-generator-macos
        asset_content_type: application/octet-stream
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./readable-name-generator-windows-latest/readable-name-generator
        asset_name: readable-name-generator-windows.exe
        asset_content_type: application/octet-stream
  github-docker-build-release:
    needs: [test, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: purplebooth/readable-name-generator/readable-name-generator
          username: PurpleBooth
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_names: true
  github-docker-build-latest:
    needs: [test, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: purplebooth/readable-name-generator/readable-name-generator
          username: PurpleBooth
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
  docker-hub-docker-build-release:
    needs: [test, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: purplebooth/readable-name-generator
          username: purplebooth
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tag_names: true
  docker-hub-docker-build-latest:
    needs: [test, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: purplebooth/readable-name-generator
          username: purplebooth
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
