on:
  schedule:
    - cron:  '0 12 * * 1-5'
  push: ~
  pull_request: ~
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v1
      - run: |
          if [ "$PLATFORM_NAME" == "windows-latest" ] ; then
            make test-universal
          else
            make test
          fi
        env:
          PLATFORM_NAME: ${{ matrix.platform }}

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: |
          docker build -t ci .
          docker run --rm ci
