'on':
  push:
    tags:
      - '*'
jobs:
  generate-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cuchi/jinja2-action@v1.1.0
        with:
          template: homebrew/formula.rb.j2
          output_file: formula.rb
          variables: |
            github_repo=${{ github.repository }}
            git_tag=${{ github.ref }}
            git_sha=${{ github.sha }}
      - uses: actions/upload-artifact@v2
        with:
          name: formula
          path: ./formula.rb
  build:
    needs:
      - generate-formula
    runs-on: macos-latest
    steps:
      - id: get_repository_name
        run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
        shell: bash
      - uses: actions/download-artifact@v2
      - uses: actions/checkout@v2
        with:
          repository: PurpleBooth/homebrew-repo
          token: ${{ secrets.COMMITTER_TOKEN }}
          path: homebrew-repo
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          path: source-repo
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - id: get-brew-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.get-brew-cache.outputs.dir }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/formula.rb.j2') }}
      - shell: bash
        run: |
          set -euo pipefail
          FORMULA_LOCATION="homebrew-repo/Formula/$REPOSITORY_NAME.rb"

          if [ ! -f "$FORMULA_LOCATION" ] || ! grep -q $GITHUB_SHA "$FORMULA_LOCATION" ; then
            cp formula/formula.rb "homebrew-repo/Formula/$REPOSITORY_NAME.rb"
          fi

          cp -r ./homebrew-repo/. "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"

          cd "$(brew --repo)/Library/Taps/purplebooth/homebrew-repo"

          brew test-bot \
            --bintray-org="$BINTRAY_ORG" \
            --root-url="$BINTRAY_DL_URL" \
            "purplebooth/repo/$REPOSITORY_NAME"

          curl \
            "$BINTRAY_API_URL/packages/$BINTRAY_ORG/$PACKAGE" \
            -u "$HOMEBREW_BINTRAY_USER:$HOMEBREW_BINTRAY_KEY" \
            -X POST \
            -H 'Content-Type: application/json' \
            -d "{ \"name\": \"$PACKAGE\", \"vcs_url\": \"https://github.com/PurpleBooth/$PACKAGE.git\", \"github_repo\": \"PurpleBooth/$PACKAGE\", \"public_download_numbers\": true, \"public_stats\": true }" ||
            echo "Package probably already exists..."

          brew test-bot \
            --ci-upload \
            --bintray-org="$BINTRAY_ORG" \
            --root-url="$BINTRAY_DL_URL" \
            --publish

          git pull --rebase
          git push
        env:
          REPOSITORY_NAME: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}
          GITHUB_SHA: ${{ github.sha }}
          BINTRAY_API_URL: https://api.bintray.com
          BINTRAY_DL_URL: https://dl.bintray.com/purplebooth/bottles-repo
          BINTRAY_ORG: purplebooth
          HOMEBREW_BINTRAY_USER: purplebooth
          HOMEBREW_BINTRAY_KEY: '${{ secrets.HOMEBREW_BINTRAY_KEY }}'
